<?php
	include "common/connect.php";
	include "common/headinfo.php";
	include "common/structuretop.php";
?>
<table border="0" cellpadding="3" cellspacing="1" width="645" align="center">
	<tr>
		<td class="highlight"><span class="headline">LaunchPages.com Terms of Service Agreement</span></td>
	</tr>
	<tr>
		<td style="text-align: justify;">
			Welcome to LaunchPages.com, an online link database that allows you to access your favorite URL's anytime anywhere. The LaunchPages.com service is operated by <a href="http://www.garciaramon.com">Ramon Garcia</a> ("LaunchPages.com"). By using the LaunchPages.com web site (the "Web site") you agree to be bound by these Terms of Service (this "Agreement"). If you wish to become a Member of the LaunchPages.com service (the "Service"), read these Terms of Service and indicate your acceptance of them by following the instructions in the Sign Up page.
			<br/><br/>
			This Agreement sets out the legally binding terms of your use of the Web site and your membership in the Service and may be modified by LaunchPages.com at any time and without prior notice, such modifications to be effective upon posting by LaunchPages.com on the Web site. This Agreement includes LaunchPages.com's acceptable use policy for content posted on the web site, LaunchPages.com's Privacy Policy, and any notices regarding the Web site.
			<ol>
				<li><span class="headline">Eligibility</span>. You must be sixteen or over to register as a member of LaunchPages.com or use the Web site. Membership in the Service is void where prohibited. By using the Web site, you represent and warrant that you have the right, authority, and capacity to enter into this Agreement and to abide by all of the terms and conditions of this Agreement.</li>
				<li><span class="headline">Term</span>. This Agreement will remain in full force and effect while you use the Web site and/or are a Member. LaunchPages.com may terminate your membership for any reason, at any time. If LaunchPages.com terminates your membership in the Service because you have breached the Agreement, you will not be entitled to any refund of unused subscription fees. Even after membership is terminated, this Agreement will remain in effect.</li>
				<li><span class="headline">Non Commercial Use by Members</span>. The Web site is for the personal use of individual Members only and may not be used in connection with any commercial endeavors. Passwords, photos, links, and Web site content are not to be transferred or copied from the Web site for use with any other product or service. Illegal and/or unauthorized uses of the Web site, including collecting usernames and/or email addresses of members by electronic or other means for the purpose of sending unsolicited email and unauthorized framing of or linking to the Web site will be investigated, and appropriate legal action will be taken, including without limitation, civil, criminal, and injunctive redress.</li>
				<li><span class="headline">Proprietary Rights in Content on LaunchPages.com</span>. LaunchPages.com owns and retains all proprietary rights in the Web site and the Service. The Web site contains the copyrighted material, including links and compilations of individual data, trademarks, and other proprietary information of LaunchPages.com, and its licensors. Except for that information which is in the public domain or for which you have been given written permission, you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information.</li>
				<li><span class="headline">Content Posted on the Site</span>.
					<ol>
						<li>You understand and agree that LaunchPages.com may review and delete any content, messages, photos or profiles (collectively, "Content") that in the sole judgment of LaunchPages.com violate this Agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of Members.</li>
						<li>Your profile must describe you, an individual person. Examples of inappropriate profiles include, but are not limited to, profiles that purport to represent an animal, place, inanimate object, fictional character, or real individual who is not you.</li>
						<li>You are solely responsible for the Content that you publish or display (hereinafter, "post") on the Service, or transmit to other Members.</li>
						<li>By posting Content to any public area of LaunchPages.com, you automatically grant, and you represent and warrant that you have the right to grant, to LaunchPages.com an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, and distribute such information and content and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sublicenses of the foregoing.</li>
						<li>The following is a partial list of the kind of Content that is illegal or prohibited on the Web site. LaunchPages.com reserves the right to investigate and take appropriate legal action in its sole discretion against anyone who violates this provision, including without limitation, removing the offending communication from the Service and terminating the membership of such violators. It includes Content that:
							<ul>
								<li>is patently offensive to the online community, such as Content that promotes racism, bigotry , hatred or physical harm of any kind against any group or individual;</li>
								<li>harasses or advocates harassment of another person;</li>
								<li>involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming";</li>
								<li>promotes information that you know is false, misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;</li>
								<li>promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;</li>
								<li>contains restricted or password only access pages, or hidden pages or images (those not linked to or from another accessible page) ;</li>
								<li>displays pornographic or sexually explicit material of any kind;</li>
								<li>provides material that exploits people under the age of 18 in a sexual or violent manner, or solicits personal information from anyone under 18;</li>
								<li>provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;</li>
								<li>solicits passwords or personal identifying information for commercial or unlawful purposes from other users; and</li>
								<li>engages in commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising, and pyramid schemes;</li>
								<li>solicits people you don't know to add you or accept you as a friend on LaunchPages.com.</li>
							</ul>
							Even though all of this is strictly prohibited, there is a small chance that You might become exposed to such items and You further waive Your right to any damages (from any party) related to such exposure.
						</li>
						<li>You must use the Service in a manner consistent with any and all applicable laws and regulations.</li>
						<li>You may not include in your Member profile any telephone numbers, street addresses, last names, URLs or email addresses.</li>
						<li>You may not engage in advertising to, or solicitation of, other Members to buy or sell any products or services through the Service. You may not transmit any chain letters or junk email to other Members. Although LaunchPages.com cannot monitor the conduct of its Members off the Web site, it is also a violation of these rules to use any information obtained from the Service in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to any Member without their prior explicit consent. In order to protect our Members from such advertising or solicitation, LaunchPages.com reserves the right to restrict the number of emails which a Member may send to other Members in any 24-hour period to a number which LaunchPages.com deems appropriate in its sole discretion.</li>
					</ol>
				</li>
				<li><span class="headline">Copyright Policy</span>. You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. Without limiting the foregoing, if you believe that your work has been copied and posted on the Service in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; a description of the copyrighted work that you claim has been infringed; a description of where the material that you claim is infringing is located on the Web site; your address, telephone number, and email address; a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. LaunchPages.com's Copyright Agent for notice of claims of copyright infringement can be reached as follows: Copyright Agent, LaunchPages.com, Inc. 415 N. Mary Ave., Suite 112-280, Sunnyvale, CA 94085.</li>
				<li><span class="headline">Member Disputes</span>. You are solely responsible for your interactions with other LaunchPages.com Members. LaunchPages.com, Inc. reserves the right, but has no obligation, to monitor disputes between you and other Members.</li>
				<li><span class="headline">Privacy</span>. Use of the Web site and/or the Service is also governed by our Privacy Policy.</li>
				<li><span class="headline">Disclaimers</span>. LaunchPages.com is not responsible for any incorrect or inaccurate Content posted on the Web site or in connection with the Service, whether caused by users of the Web site, Members or by any of the equipment or programming associated with or utilized in the Service. LaunchPages.com is not responsible for the conduct, whether online or offline, of any user of the Web site or Member of the Service. LaunchPages.com assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, user or Member communications. LaunchPages.com is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any web site or combination thereof, including injury or damage to users and/or Members or to any other person's computer related to or resulting from participating or downloading materials in connection with the Web and/or in connection with the Service. Under no circumstances will LaunchPages.com be responsible for any loss or damage, including personal injury or death, resulting from anyone's use of the Web site or the Service, any Content posted on the Web site or transmitted to Members, or any interactions between users of the Web site, whether online or offline. The Web site and the Service are provided "AS-IS" and LaunchPages.com expressly disclaims any warranty of fitness for a particular purpose or non-infringement. LaunchPages.com cannot guarantee and does not promise any specific results from use of the Web site and/or the Service. The service may be temporarily unavailable from time to time for maintenance or other reasons. No advice or information, whether oral or written, obtained by user from LaunchPages.com or through or from the service shall create any warranty not expressly stated herein.</li>
				<li><span class="headline">Limitation on Liability</span>. Except in jurisdictions where such provisions are restricted, in no event will LaunchPages.com be liable to you or any third person for any indirect, consequential, exemplary, incidental, special or punitive damages, including also lost profits arising from your use of the Web site or the Service, even if LaunchPages.com has been advised of the possibility of such damages. Notwithstanding anything to the contrary contained herein, LaunchPages.com's liability to you for any cause whatsoever, and regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to LaunchPages.com for the Service during the term of membership.</li>
				<li><span class="headline">Disputes</span>. If there is any dispute about or involving the Web site and/or the Service, by using the Web site, you agree that the dispute will be governed by the laws of the State of California without regard to its conflict of law provisions. You agree to personal jurisdiction by and venue in the state and federal courts of the State of California, City of Sunnyvale.</li>
				<li><span class="headline">Indemnity</span>. You agree to indemnify and hold LaunchPages.com, its subsidiaries, affiliates, officers, agents, and other partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorney's fees, made by any third party due to or arising out of your use of the Service in violation of this Agreement and/or arising from a breach of this Agreement and/or any breach of your representations and warranties set forth above. If You are a California resident, You waive California Civil Code Section 1542, which says "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor."</li>
				<li><span class="headline">No Agency</span>. There is no agency, partnership, joint venture, employee-employer or franchisor-franchisee relationship between LaunchPages.com and any User of the Service.</li>
				<li><span class="headline">Other</span>. This Agreement, accepted upon use of the Web site and further affirmed by becoming a Member of the Service, contains the entire agreement between you and LaunchPages.com regarding the use of the Web site and/or the Service. The failure of LaunchPages.com to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision. If any provision of this Agreement is held invalid, the remainder of this Agreement shall continue in full force and effect. The section titles in these Terms of Service are for convenience only and have no legal or contractual effect.
			</ol>
			Please <a href="contact.php">contact us</a> with any questions regarding this agreement. 
		</td>
	</tr>
</table>
<?php	include "common/structurebottom.php"; ?>
